petclinic {
  database {
    jdbcUrl = ${?JDBC_URL}
    user = ${?DB_USER}
    password = ${?DB_PASSWORD}
    poolSize = ${?DB_POOL_SIZE}
  }

  serverHost = "localhost"
  serverHost = ${?SERVER_HOST}
}
